server:
  port: 8025


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/micro-services
    username: Gopal
    password: Gopal
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: configserver:http://localhost:8029
  application:
    name: USER-SERVICE

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:  https://dev-08758528.okta.com/oauth2/default
      client:
        registration:

          my-internal-client:
            provider: okta
            authorizationGrantType: client credentials
            scope: internal
            clientId: 0oa9nhza02lGDAYlW5d7
            clientSecret: 60APPNdIkeVS1GozaHtv8Qz0t2zL_qXp0GtdBnvs
        provider:
          okta:
            issuerUri: https://dev-08758528.okta.com/oauth2/default




#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

management:
  health:
    circuit-breakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      ratingHotelservice:
        maxAttempts: 3
        waitDuration: 5s


okta:
  oauth2:
    issuer: https://dev-08758528.okta.com/oauth2/default
    audience:  api://default