server:
  port: 8027

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/micro-services-rating
    username: Gopal
    password: Gopal
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: RATING-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

okta:
  oauth2:
    issuer: https://dev-08758528.okta.com/oauth2/default
    audience:  api://default